parameters:
#    street_vc_base.example.class: StreetVC\BaseBundle\Example

services:
#    street_vc_base.example:
#        class: %street_vc_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
