imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: [ bancbox ]
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: notice
        firephp:
            type:  firephp
            level: error
        chromephp:
            type:  chromephp
            level: warning
        bancbox:
            channels: [ bancbox ]
            path: "%kernel.logs_dir%/bancbox.log"
            level: debug
            type: stream

assetic:
    use_controller: true

server_grove_translation_editor:
  storage:
    type: server_grove_translation_editor.storage.mongodb
    manager: doctrine_mongodb.odm.document_manager

#swiftmailer:
#    delivery_address: me@example.com
