sg_localeditor_index:
    pattern:  /editor
    defaults: { _controller: StreetVCTranslationBundle:Editor:index }

sg_localeditor_update_translation:
    pattern:  /update-translation
    defaults: { _controller: StreetVCTranslationBundle:Editor:updateTranslation }

sg_localeditor_add_translation:
    pattern:  /add-translation
    defaults: { _controller: StreetVCTranslationBundle:Editor:addTranslation }

sg_localeditor_remove_translation:
    pattern:  /remove-translation
    defaults: { _controller: StreetVCTranslationBundle:Editor:removeTranslation }

sg_localeditor_add_locale:
    pattern:  /add-locale
    defaults: { _controller: StreetVCTranslationBundle:Editor:addLocale }

sg_localeditor_remove_locale:
    pattern:  /remove-locale
    defaults: { _controller: StreetVCTranslationBundle:Editor:removeLocale }
