<?php
namespace StreetVC\LoanBundle\Document;


/**
 * Test class for Loan.
 * Generated by PHPUnit on 2014-07-15 at 13:24:49.
 */
class LoanTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Loan
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Loan;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testIsCreatedWithId()
    {
        $this->assertNotNull($this->object->getId());
    }

    public function testIsCreatedWithInitialState()
    {
        $this->assertEquals($this->object->getState(), Loan::STATE_INITIAL);
    }

}